-- Limpa tabelas e reinicia identidades (H2)
SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE tb_product_category;
TRUNCATE TABLE tb_product;
TRUNCATE TABLE tb_category;
SET REFERENTIAL_INTEGRITY TRUE;

ALTER TABLE tb_product  ALTER COLUMN id RESTART WITH 1;
ALTER TABLE tb_category ALTER COLUMN id RESTART WITH 1;
