SET NAMES utf8mb4;
SET time_zone = '+00:00';

START TRANSACTION;

-- ROLES
INSERT INTO tb_role (authority) VALUES ('ROLE_CLIENT');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');

-- CATEGORIES
INSERT INTO tb_category(name) VALUES ('Livros');
INSERT INTO tb_category(name) VALUES ('Eletrônicos');
INSERT INTO tb_category(name) VALUES ('Computadores');
INSERT INTO tb_category(name) VALUES ('Smartphones');
INSERT INTO tb_category(name) VALUES ('Games');
INSERT INTO tb_category(name) VALUES ('Acessórios');
INSERT INTO tb_category(name) VALUES ('Livros Técnicos');

-- PRODUCTS (1..45)
INSERT INTO tb_product (name, price, description, img_url) VALUES ('The Lord of the Rings', 90.5, 'Obra-prima de fantasia épica de J. R. R. Tolkien sobre a jornada para destruir o Um Anel; mundo rico, personagens memoráveis e aventura clássica.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Smart TV', 2190.0, 'TV 4K com sistema Smart para apps de streaming, Wi-Fi integrado e controle por voz; imagem nítida para filmes, séries e esportes.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/2-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Macbook Pro', 1250.0, 'Notebook macOS voltado a profissionais, tela de alta definição, bateria de longa duração e desempenho estável para desenvolvimento e edição.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/3-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer', 1200.0, 'Desktop para jogos com fluxo de ar eficiente e fácil expansão; ideal para partidas competitivas em 1080p com alta taxa de quadros.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/4-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Rails for Dummies', 100.99, 'Introdução prática a Ruby on Rails: MVC, scaffolds, rotas, Active Record e boas práticas para construir aplicações web rapidamente.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/5-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Ex', 1350.0, 'Configuração balanceada com GPU dedicada e SSD para carregamentos rápidos; pronto para jogos populares e multitarefa.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/6-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer X', 1350.0, 'Foco em custo-benefício: desempenho sólido em 1080p, gabinete compacto e espaço para upgrades futuros.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/7-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Alfa', 1850.0, 'PC para 1440p com boa refrigeração e componentes selecionados para estabilidade, ideal para jogos AAA e criação de conteúdo.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/8-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Tera', 1950.0, 'Desempenho forte para jogos, streaming e multitarefas; pronto para placas de vídeo de última geração e expansão de memória.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/9-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Y', 1700.0, 'Torre compacta com boa ventilação, SSD para inicialização rápida e desempenho consistente em e-sports.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/10-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Nitro', 1450.0, 'Build otimizada para taxa de quadros alta em 1080p; ideal para jogos competitivos e streaming ocasional.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/11-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Card', 1850.0, 'Configuração versátil para jogos e edição leve, com armazenamento híbrido e amplo espaço para upgrades.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/12-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Plus', 1350.0, 'PC de entrada robusto com SSD e memórias rápidas; indicado para estudo, trabalho e jogos populares.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/13-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Hera', 2250.0, 'Alto desempenho com refrigeração reforçada e gabinete com iluminação; preparado para jogos pesados e multitarefas.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/14-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Weed', 2200.0, 'Plataforma estável para longas sessões de jogo, com foco em silêncio e temperaturas controladas.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/15-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Max', 2340.0, 'Topo de linha para 1440p/4K leve, excelente multitarefa e grande capacidade de armazenamento.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/16-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Turbo', 1280.0, 'Projeto enxuto com foco em alto clock e resposta rápida; ideal para e-sports e títulos menos exigentes.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/17-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Hot', 1450.0, 'Equilíbrio entre desempenho e preço, pronto para monitores 1080p de alta taxa de atualização.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/18-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Ez', 1750.0, 'Fácil de manter e atualizar, com armazenamento rápido e forte desempenho em jogos competitivos.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/19-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Tr', 1650.0, 'Conjunto equilibrado para jogos e tarefas criativas, com bom potencial de upgrade.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/20-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Tx', 1680.0, 'Pensado para 1080p/144 Hz, com foco em estabilidade e baixo tempo de carregamento.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/21-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Er', 1850.0, 'Estação de jogo e estudo com boa refrigeração e SSD NVMe para responsividade.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/22-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Min', 2250.0, 'Formato compacto com desempenho de desktop, baixo ruído e excelente eficiência térmica.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/23-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Boo', 2350.0, 'Build silenciosa com foco em qualidade de componentes e durabilidade para uso intenso.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/24-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PC Gamer Foo', 4170.0, 'Configurado para entusiastas, pronto para 4K leve e produção de conteúdo com múltiplas aplicações abertas.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/25-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('iPhone 13', 4999.0, 'Smartphone Apple com tela Super Retina XDR de 6,1", chip A15 Bionic, câmeras avançadas e conectividade 5G.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Galaxy S22', 3999.0, 'Smartphone com tela 6,1" FHD+ Dynamic AMOLED 2X de 120 Hz, conjunto de câmeras versátil e 5G.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/2-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Headset Gamer Pro', 350.0, 'Headset com áudio estéreo claro, microfone com redução de ruído e almofadas confortáveis; ideal para jogos e chamadas.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/3-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Mouse Gamer RGB', 180.0, 'Mouse com sensor preciso ajustável, switches duráveis e iluminação RGB personalizável.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/4-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Teclado Mecânico Blue Switch', 420.0, 'Teclado mecânico com switches azuis táteis e audíveis, anti-ghosting e construção resistente para digitação e jogos.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/5-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Nintendo Switch', 2199.0, 'Console híbrido jogável na TV via dock ou no modo portátil; Joy-Con destacáveis e multiplayer local/online.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/6-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('PlayStation 5', 4599.0, 'Console com SSD ultrarrápido, suporte a gatilhos adaptativos, feedback háptico e áudio 3D para maior imersão.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/7-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Xbox Series S', 2799.0, 'Console all-digital compacto, voltado a 1440p e até 120 fps, com SSD para carregamentos rápidos.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/8-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Kindle Paperwhite', 649.0, 'Leitor digital com tela de 6,8" sem reflexos, luz ajustável, bateria longa e resistência à água para leitura em qualquer lugar.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/9-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Docker Deep Dive', 159.9, 'Guia prático de contêineres: imagens, redes, volumes e orquestração; fundamentos essenciais do ecossistema Docker.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/10-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Clean Code', 199.0, 'Clássico sobre princípios, padrões e sinais de alerta para escrever código legível, testável e sustentável.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/11-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Effective Java', 249.9, 'Boas práticas de Java moderno: criação e destruição de objetos, coleções, genéricos, lambdas, imutabilidade e muito mais.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/12-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Spring in Action', 279.9, 'Visão prática do ecossistema Spring: Core, MVC, Data, Security e Boot com exemplos do dia a dia.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/13-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Kotlin in Action', 299.9, 'Introdução aprofundada à linguagem Kotlin: null safety, funções de extensão, DSLs e interoperabilidade com Java.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/14-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Estruturas de Dados em Java', 229.9, 'Abordagem prática de listas, pilhas, filas, árvores e grafos em Java com análise de complexidade e exemplos.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/15-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Monitor 27\" 144Hz', 1599.0, 'Monitor gamer de 27\" com taxa de atualização de 144 Hz e baixa latência; fluidez para FPS e jogos competitivos.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/16-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('SSD NVMe 1TB', 499.9, 'SSD M.2 NVMe de 1 TB para inicialização rápida e carregamentos ágeis; ideal para sistema e jogos.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/17-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Roteador Wi-Fi 6', 399.9, 'Roteador com padrão 802.11ax (Wi-Fi 6), maior eficiência em ambientes com muitos dispositivos e melhor cobertura.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/18-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Webcam 1080p', 229.9, 'Webcam Full HD 1080p com autofoco e correção automática de luz; indicada para videochamadas e streaming.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/19-big.jpg');
INSERT INTO tb_product (name, price, description, img_url) VALUES ('Cadeira Gamer', 899.0, 'Cadeira ergonômica com apoio lombar e regulagens de altura e inclinação; conforto para longas sessões.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/20-big.jpg');

-- PRODUCT_CATEGORY
INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (5, 7);
INSERT INTO tb_product_category (product_id, category_id) VALUES (5, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (35, 7);
INSERT INTO tb_product_category (product_id, category_id) VALUES (36, 7);
INSERT INTO tb_product_category (product_id, category_id) VALUES (37, 7);
INSERT INTO tb_product_category (product_id, category_id) VALUES (38, 7);
INSERT INTO tb_product_category (product_id, category_id) VALUES (39, 7);
INSERT INTO tb_product_category (product_id, category_id) VALUES (40, 7);
INSERT INTO tb_product_category (product_id, category_id) VALUES (34, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (34, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (26, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (26, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (27, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (27, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (31, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (31, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (32, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (32, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (33, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (33, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (3, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (3, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (21, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (21, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (22, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (22, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (23, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (23, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (24, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (24, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (25, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (25, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (28, 6);
INSERT INTO tb_product_category (product_id, category_id) VALUES (28, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (29, 6);
INSERT INTO tb_product_category (product_id, category_id) VALUES (29, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (30, 6);
INSERT INTO tb_product_category (product_id, category_id) VALUES (30, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (44, 6);
INSERT INTO tb_product_category (product_id, category_id) VALUES (44, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (45, 6);
INSERT INTO tb_product_category (product_id, category_id) VALUES (45, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (41, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (41, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (42, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (42, 6);
INSERT INTO tb_product_category (product_id, category_id) VALUES (43, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (43, 6);

-- USERS
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Maria Brown', 'maria@gmail.com', '988888888', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '2001-07-25');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Alex Green', 'alex@gmail.com', '977777777', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1987-12-13');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Vinícius dos Santos Andrade', 'vinicius_andrade2010@hotmail.com', '19974133884','$2a$10$YXAZx7Pmio.awFvF.Zdh5ObohVRx/SCJ4rB7LPx5A2qNsIp2L0VYa', '2001-12-06');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Vinícius dos Santos Andrade', 'vinicius_andrade2011@hotmail.com', '19974133884','$2a$10$YXAZx7Pmio.awFvF.Zdh5ObohVRx/SCJ4rB7LPx5A2qNsIp2L0VYa', STR_TO_DATE('06/12/2001','%d/%m/%Y'));
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Vinícius dos Santos Andrade', 'vinicius_andrade2012@hotmail.com', '19974133884','$2a$10$YXAZx7Pmio.awFvF.Zdh5ObohVRx/SCJ4rB7LPx5A2qNsIp2L0VYa', STR_TO_DATE('06-12-2001','%d-%m-%Y'));
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Bob Grey', 'bob@gmail.com', '966666666', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1999-03-10');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Anna White', 'anna@gmail.com', '955555555', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1995-11-05');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('John Black', 'john@gmail.com', '944444444', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '2000-01-20');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Carol King',   'carol@gmail.com',   '933333333', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1998-06-17');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Daniel Craig', 'daniel@gmail.com',  '922222222', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1992-02-04');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Eva Stone',    'eva@gmail.com',     '911111111', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1996-09-28');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Frank Miller', 'frank@gmail.com',   '900000000', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1985-01-15');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Grace Brown',  'grace@gmail.com',   '989898989', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1988-12-09');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Henry Wilson', 'henry@gmail.com',   '979797979', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1975-07-07');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Ivy Clark',    'ivy@gmail.com',     '969696969', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '2002-03-12');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Jack Ryan',    'jack@gmail.com',    '959595959', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1993-05-23');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Lara Croft',   'lara@gmail.com',    '949494949', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1994-08-14');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Nina Simone',  'nina@gmail.com',    '939393939', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1987-02-21');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Oliver Queen', 'oliver@gmail.com',  '929292929', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1991-10-18');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Paula Adams',  'paula@gmail.com',   '919191919', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1998-05-01');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Quentin Blake','quentin@gmail.com', '909090909', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1978-11-11');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Rachel Green', 'rachel@gmail.com',  '898989898', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1990-05-05');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Steve Rogers', 'steve@gmail.com',   '888888888', '$2a$10$N7SkKCa3r17ga.i.dF9iy.BFUBL2n3b6Z1CWSZWi/qy7ABq/E6VpO', '1984-07-04');

-- USER_ROLE
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (4, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (4, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (5, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (6, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (7, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (8, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (9, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (10, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (10, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (11, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (12, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (13, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (14, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (15, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (16, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (17, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (18, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (19, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (19, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (20, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (21, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (22, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (23, 1);

-- ORDERS (moments em UTC por conta do SET time_zone = '+00:00')
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-07-25 13:00:00', 1, 1);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-07-29 15:50:00', 3, 2);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-03 14:20:00', 0, 1);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-10 10:00:00', 1, 3);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-12 09:30:00', 0, 4);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-15 18:45:00', 2, 3);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-18 13:15:00', 3, 5);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-20 16:25:00', 1, 4);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-22 10:10:00', 1, 6);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-22 12:30:00', 0, 7);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-23 09:00:00', 2, 8);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-23 16:45:00', 3, 9);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-24 08:20:00', 4, 10);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-24 11:05:00', 1, 11);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-25 13:30:00', 2, 12);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-25 17:50:00', 0, 13);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-26 07:40:00', 3, 14);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-26 14:25:00', 1, 15);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-27 10:10:00', 2, 3);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-27 15:15:00', 4, 4);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-28 09:00:00', 1, 5);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-28 13:45:00', 3, 6);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-29 08:00:00', 0, 7);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-29 16:20:00', 2, 8);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-30 10:55:00', 1, 9);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-30 18:35:00', 3, 10);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-31 11:11:00', 0, 11);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-08-31 19:05:00', 1, 12);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-09-01 09:00:00', 2, 16);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-09-01 13:20:00', 1, 17);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-09-02 10:10:00', 0, 18);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-09-02 15:00:00', 3, 19);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-09-03 08:45:00', 1, 20);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-09-03 14:10:00', 4, 16);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-09-04 11:30:00', 2, 17);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-09-04 18:00:00', 3, 18);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-09-05 10:00:00', 1, 19);
INSERT INTO tb_order (moment, status, client_id) VALUES ('2022-09-05 16:40:00', 0, 20);

-- ORDER_ITEMS
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (4, 26, 1, 4999.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (4, 29, 2, 180.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (5, 32, 1, 4599.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (6, 41, 1, 1599.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (6, 42, 1, 499.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (7, 36, 1, 199.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (7, 37, 1, 249.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (7, 38, 1, 279.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (8, 31, 1, 2199.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (8, 43, 1, 399.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (9, 34, 1, 649.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (10, 41, 1, 1599.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (10, 42, 2, 499.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (11, 26, 1, 4999.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (12, 36, 1, 199.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (12, 37, 1, 249.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (13, 31, 1, 2199.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (14, 45, 1, 899.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (14, 28, 1, 350.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (15, 2, 1, 2190.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (16, 5, 1, 100.99);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (16, 1, 2, 90.5);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (17, 16, 1, 2340.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (17, 42, 1, 499.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (18, 33, 1, 2799.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (19, 32, 1, 4599.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (19, 43, 1, 399.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (20, 25, 1, 4170.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (21, 35, 1, 159.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (21, 36, 1, 199.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (21, 40, 1, 229.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (22, 11, 1, 1450.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (23, 27, 1, 3999.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (24, 29, 2, 180.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (24, 30, 1, 420.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (25, 41, 2, 1599.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (26, 7, 1, 1350.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (26, 42, 1, 499.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (26, 44, 1, 229.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (27, 14, 1, 2250.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (28, 3, 1, 1250.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (28, 34, 1, 649.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (29, 31, 1, 2199.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (29, 43, 1, 399.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (30, 45, 1, 899.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (31, 21, 1, 1680.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (32, 36, 1, 199.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (32, 35, 1, 159.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (33, 41, 1, 1599.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (33, 42, 2, 499.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (34, 26, 1, 4999.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (35, 32, 1, 4599.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (36, 39, 1, 299.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (36, 38, 1, 279.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (37, 1, 1, 90.5);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (37, 34, 1, 649.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (38, 33, 1, 2799.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (1, 1, 2, 90.5);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (1, 3, 1, 1250.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (2, 3, 1, 1250.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (3, 1, 1, 90.5);

-- PAYMENTS (converter 'TIMESTAMP WITH TIME ZONE' -> 'YYYY-MM-DD HH:MM:SS')
INSERT INTO tb_payment (order_id, moment) VALUES (1,  '2022-07-25 15:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (2,  '2022-07-30 11:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (4,  '2022-08-10 12:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (6,  '2022-08-15 20:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (7,  '2022-08-18 15:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (8,  '2022-08-20 18:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (9,  '2022-08-22 12:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (11, '2022-08-23 10:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (12, '2022-08-23 18:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (14, '2022-08-24 12:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (15, '2022-08-25 15:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (17, '2022-08-26 09:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (18, '2022-08-26 16:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (19, '2022-08-27 12:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (21, '2022-08-28 10:30:00');
INSERT INTO tb_payment (order_id, moment) VALUES (22, '2022-08-28 15:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (24, '2022-08-29 18:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (25, '2022-08-30 12:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (26, '2022-08-30 20:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (28, '2022-08-31 21:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (29, '2022-09-01 11:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (30, '2022-09-01 15:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (32, '2022-09-02 17:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (33, '2022-09-03 10:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (35, '2022-09-04 13:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (36, '2022-09-04 20:00:00');
INSERT INTO tb_payment (order_id, moment) VALUES (37, '2022-09-05 12:30:00');

COMMIT;

-- Reativar FKs
SET FOREIGN_KEY_CHECKS = 1;
