SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE tb_user_role;
TRUNCATE TABLE tb_role;
TRUNCATE TABLE tb_user;

ALTER TABLE tb_user ALTER COLUMN id RESTART WITH 1;
ALTER TABLE tb_role ALTER COLUMN id RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;